FitFox/Controllers/HomeController.cs
using FitFox.Data.Models;
using FitFox.Models;
using FitFox.Services.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FitFox.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
		private readonly IApplicationUserService _userService;
		private readonly UserManager<ApplicationUser> _userManager;

		public HomeController(ILogger<HomeController> logger,
							IApplicationUserService userService,
							UserManager<ApplicationUser> userManager)
		{
			_userManager = userManager;
			_userService = userService;
			_logger = logger;
		}

		[Authorize]
		public async Task<IActionResult> Index()
		{
			var user = await _userManager.GetUserAsync(User);
			if (user == null)
			{
				return Unauthorized();
			}

			var achievementsGranted = await _userService.CheckForAchievementsToGrantAsync(user.Id);

			return View(achievementsGranted.achievementsGranted);
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpGet]
		[Authorize]
		public async Task<IActionResult> UserAchievements()
		{
			var user = await _userManager.GetUserAsync(User);
			if (user == null)
			{
				return Unauthorized();
			}
			var result = await _userService.FetchUserInfoAsync(user.Id);

			return View(result);
		}
	}
}

FitFox/Controllers/MapController.cs
using FitFox.Data.Models;
using FitFox.Services.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FitFox.Controllers
{
	[Authorize]
	public class MapController : Controller
	{
		private readonly IMapService _mapService;
		private readonly IApplicationUserService _userService;
		private readonly UserManager<ApplicationUser> _userManager;
		public MapController(IMapService mapService, UserManager<ApplicationUser> userManager, IApplicationUserService userService)
		{
			_mapService = mapService;
			_userService = userService;
			_userManager = userManager;
		}

		[HttpGet]
		public async Task<IActionResult> GetAllMaps()
		{
			var outputModel = await _mapService.GetAllMapsAsync();
			return View(outputModel);
		}

		[HttpPost]
		public async Task<IActionResult> StartMap(Guid mapId)
		{
			var user = await _userManager.GetUserAsync(User);

			if (user == null)
			{
				return Unauthorized();
			}

			await _userService.StartMapForUserAsync(mapId, user.Id);

			return RedirectToAction("GetMapLessons", "Lesson", new { mapId });
		}
	}
}

FitFox/Views/Home/Index.cshtml
@using FitFox.Web.ViewModels.Achievement;
@model IEnumerable<AchievementGrantedViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="home-page">
    <div id="achievement-popup" class="achievement-popup">
        🎉 Congrats! You unlocked an achievement!
    </div>
    @if (Model != null && Model.Any())
    {
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                let delay =  0;
                @foreach (var ach in Model)
                {
                     @:setTimeout(() => showAchievementPopup("@ach.Title"), delay);
                     @:delay += 3500;
                }
            });
        </script>
    }
    <h1 class="display-4">Welcome to FitFox!</h1>
    <img class="fit-fox-character" src="~/TheFitFoxCharacter.png"/>
    <div class="choose-activity">
        <div class="choose-activity-start-learning">
            <h2>Start Learning</h2>
            <a asp-controller="Map" asp-action="GetAllMaps">Choose a map</a>
        </div>
        <div class="choose-activity-daily-quests">
            <h2>Daily lesson</h2>
            <a href="">Choose a map</a>
        </div>
    </div>
</div>
<script>
        function showAchievementPopup(message, duration = 3000) {
        const popup = document.getElementById("achievement-popup");
        popup.textContent = "🎉 " + message;
        popup.style.opacity = 1; // fade in
        popup.style.pointerEvents = "auto";

        setTimeout(() => {
            popup.style.opacity = 0; // fade out
            popup.style.pointerEvents = "none";
        }, duration);
    }
</script>

FitFox/Views/Home/UserAchievements.cshtml
@using FitFox.Web.ViewModels.Player
@model PlayerInfo

<div class="user-honor-room-wrapper">
	<h1 class="honor-room">The Honor Room</h1>


	<div class="completed-lessons">
		<h2>Completed lessons:</h2>
	</div>

	<div class="current-level">
		<h2>Level:</h2>
		<p>Level @Model.CurrentLevel.LevelNumber - @Model.CurrentLevel.LevelTitle</p>
		<p>XP:@Model.CurrentXP</p>
	</div>

	<div class="maps-coverage">
		<h2>Maps progression:</h2>
		@foreach(var kvp in Model.MapsCoverage)
		{
			<div class="single-map-coverage-box">
				<h3>@kvp.Key.Title</h3>
				<p>@kvp.Value %</p>
			</div>
		}
	</div>

	<div class="achievements">
		<h2>Achievements:</h2>
		@{
			if (Model.Achievements != null && Model.Achievements.Any())
			{
				foreach(var ach in Model.Achievements)
				{
					<div class="achievement-display-box">
						<p>@ach.Title</p>
						<img class="achievement-icon" src="@ach.IconURL" alt="@ach.Title" />
						<p>@ach.Description</p>
					</div>
				}
			}
			else
			{
				<p>Currently no achievements.</p>
			}
		}
	</div>
</div>